export const runtime = "nodejs";
export const dynamic = "force-dynamic";

import { notFound } from "next/navigation";
import { supabase } from "@/lib/db";
import { PageHeader } from "@/components/ui/PageHeader";
import { ReportViewer } from "@/components/ReportViewer";
import type { ImpactReport } from "@/lib/agents/report";

export default async function ReportPage({ params }: { params: Promise<{ reportId: string }> }) {
  const { reportId } = await params;
  if (!/^[\w-]{3,64}$/.test(reportId)) notFound();
  const { data } = await supabase.from("story").select("id, period, report, citation_coverage").eq("id", reportId).maybeSingle();
  const impact = (data?.report as { impact?: ImpactReport } | null)?.impact;
  if (!data || !impact) notFound();

  return (
    <div className="max-w-3xl space-y-8 pb-8">
      <PageHeader stage="Use · Investigate · Report" title={impact.campaignContent.headline}>
        Verified impact report generated by Pramaan multi-agent evidence investigation.
      </PageHeader>

      <ReportViewer
        impact={impact}
        citationCoverage={Number(data.citation_coverage)}
        storyId={data.id}
      />
    </div>
  );
}
